---
channel: stable
apps:
  actual-budget:
    repository: hassio-addons/app-actual-budget
    target: actual-budget
    image: ccr.ccs.tencentyun.com/hassio-addons/actual-budget
  adguard:
    repository: hassio-addons/app-adguard-home
    target: adguard
    image: ccr.ccs.tencentyun.com/hassio-addons/adguard
  aircast:
    repository: hassio-addons/app-aircast
    target: aircast
    image: ccr.ccs.tencentyun.com/hassio-addons/aircast
  airsonos:
    repository: hassio-addons/app-airsonos
    target: airsonos
    image: ccr.ccs.tencentyun.com/hassio-addons/airsonos
  appdaemon:
    repository: hassio-addons/app-appdaemon
    target: appdaemon
    image: ccr.ccs.tencentyun.com/hassio-addons/appdaemon
  audiobookshelf:
    repository: hassio-addons/app-audiobookshelf
    target: audiobookshelf
    image: ccr.ccs.tencentyun.com/hassio-addons/audiobookshelf
  bazarr:
    repository: hassio-addons/app-bazarr
    target: bazarr
    image: ccr.ccs.tencentyun.com/hassio-addons/bazarr
  bitwarden:
    repository: hassio-addons/app-vaultwarden
    target: vaultwarden
    image: ccr.ccs.tencentyun.com/hassio-addons/bitwarden
  bookstack:
    repository: hassio-addons/app-bookstack
    target: bookstack
    image: ccr.ccs.tencentyun.com/hassio-addons/bookstack
  calibre-web:
    repository: hassio-addons/app-calibre-web
    target: calibre-web
    image: ccr.ccs.tencentyun.com/hassio-addons/calibre-web
  chrony:
    repository: hassio-addons/app-chrony
    target: chrony
    image: ccr.ccs.tencentyun.com/hassio-addons/chrony
  emqx:
    repository: hassio-addons/app-emqx
    target: emqx
    image: ccr.ccs.tencentyun.com/hassio-addons/emqx
  example:
    repository: hassio-addons/app-example
    target: example
    image: ccr.ccs.tencentyun.com/hassio-addons/example
  file-explorer:
    repository: hassio-addons/app-file-explorer
    target: file-explorer
    image: ccr.ccs.tencentyun.com/hassio-addons/file-explorer
  foldingathome:
    repository: hassio-addons/app-foldingathome
    target: foldingathome
    image: ccr.ccs.tencentyun.com/hassio-addons/foldingathome
  freshrss:
    repository: hassio-addons/app-freshrss
    target: freshrss
    image: ccr.ccs.tencentyun.com/hassio-addons/freshrss
  ftp:
    repository: hassio-addons/app-ftp
    target: ftp
    image: ccr.ccs.tencentyun.com/hassio-addons/ftp
  glances:
    repository: hassio-addons/app-glances
    target: glances
    image: ccr.ccs.tencentyun.com/hassio-addons/glances
  grafana:
    repository: hassio-addons/app-grafana
    target: grafana
    image: ccr.ccs.tencentyun.com/hassio-addons/grafana
  grocy:
    repository: hassio-addons/app-grocy
    target: grocy
    image: ccr.ccs.tencentyun.com/hassio-addons/grocy
  homebox:
    repository: hassio-addons/app-homebox
    target: homebox
    image: ccr.ccs.tencentyun.com/hassio-addons/homebox
  influxdb:
    repository: hassio-addons/app-influxdb
    target: influxdb
    image: ccr.ccs.tencentyun.com/hassio-addons/influxdb
  jellyfin:
    repository: hassio-addons/app-jellyfin
    target: jellyfin
    image: ccr.ccs.tencentyun.com/hassio-addons/jellyfin
  jupyterlab:
    repository: hassio-addons/app-jupyterlab
    target: jupyterlab
    image: ccr.ccs.tencentyun.com/hassio-addons/jupyterlab
  lidarr:
    repository: hassio-addons/app-lidarr
    target: lidarr
    image: ccr.ccs.tencentyun.com/hassio-addons/lidarr
  mealie:
    repository: hassio-addons/app-mealie
    target: mealie
    image: ccr.ccs.tencentyun.com/hassio-addons/mealie
  motioneye:
    repository: hassio-addons/app-motioneye
    target: motioneye
    image: ccr.ccs.tencentyun.com/hassio-addons/motioneye
  mqtt-explorer:
    repository: hassio-addons/app-mqtt-explorer
    target: mqtt-explorer
    image: ccr.ccs.tencentyun.com/hassio-addons/mqtt-explorer
  mqtt-io:
    repository: hassio-addons/app-mqtt-io
    target: mqtt-io
    image: ccr.ccs.tencentyun.com/hassio-addons/mqtt-io
  n8n:
    repository: hassio-addons/app-n8n
    target: n8n
    image: ccr.ccs.tencentyun.com/hassio-addons/n8n
  node-red:
    repository: hassio-addons/app-node-red
    target: node-red
    image: ccr.ccs.tencentyun.com/hassio-addons/node-red
  nginxproxymanager:
    repository: hassio-addons/app-nginx-proxy-manager
    target: proxy-manager
    image: ccr.ccs.tencentyun.com/hassio-addons/nginxproxymanager
  nut:
    repository: hassio-addons/app-nut
    target: nut
    image: ccr.ccs.tencentyun.com/hassio-addons/nut
  nzbget:
    repository: hassio-addons/app-nzbget
    target: nzbget
    image: ccr.ccs.tencentyun.com/hassio-addons/nzbget
  overseerr:
    repository: hassio-addons/app-seerr
    target: seerr
    image: ccr.ccs.tencentyun.com/hassio-addons/overseerr
  phpmyadmin:
    repository: hassio-addons/app-phpmyadmin
    target: phpmyadmin
    image: ccr.ccs.tencentyun.com/hassio-addons/phpmyadmin
  plex:
    repository: hassio-addons/app-plex
    target: plex
    image: ccr.ccs.tencentyun.com/hassio-addons/plex
  qbittorrent:
    repository: hassio-addons/app-qbittorrent
    target: qbittorrent
    image: ccr.ccs.tencentyun.com/hassio-addons/qbittorrent
  radarr:
    repository: hassio-addons/app-radarr
    target: radarr
    image: ccr.ccs.tencentyun.com/hassio-addons/radarr
  sonarr:
    repository: hassio-addons/app-sonarr
    target: sonarr
    image: ccr.ccs.tencentyun.com/hassio-addons/sonarr
  spotify:
    repository: hassio-addons/app-spotify-connect
    target: spotify
    image: ccr.ccs.tencentyun.com/hassio-addons/spotify
  spotweb:
    repository: hassio-addons/app-spotweb
    target: spotweb
    image: ccr.ccs.tencentyun.com/hassio-addons/spotweb
  prowlarr:
    repository: hassio-addons/app-prowlarr
    target: prowlarr
    image: ccr.ccs.tencentyun.com/hassio-addons/prowlarr
  syncthing:
    repository: hassio-addons/app-syncthing
    target: syncthing
    image: ccr.ccs.tencentyun.com/hassio-addons/syncthing
  tailscale:
    repository: hassio-addons/app-tailscale
    target: tailscale
    image: ccr.ccs.tencentyun.com/hassio-addons/tailscale
  tasmoadmin:
    repository: hassio-addons/app-tasmoadmin
    target: tasmoadmin
    image: ccr.ccs.tencentyun.com/hassio-addons/tasmoadmin
  tautulli:
    repository: hassio-addons/app-tautulli
    target: tautulli
    image: ccr.ccs.tencentyun.com/hassio-addons/tautulli
  thelounge:
    repository: hassio-addons/app-thelounge
    target: thelounge
    image: ccr.ccs.tencentyun.com/hassio-addons/thelounge
  sabnzbd:
    repository: hassio-addons/app-sabnzbd
    target: sabnzbd
    image: ccr.ccs.tencentyun.com/hassio-addons/sabnzbd
  ssh:
    repository: hassio-addons/app-ssh
    target: ssh
    image: ccr.ccs.tencentyun.com/hassio-addons/ssh
  sqlite-web:
    repository: hassio-addons/app-sqlite-web
    target: sqlite-web
    image: ccr.ccs.tencentyun.com/hassio-addons/sqlite-web
  stirling-pdf:
    repository: hassio-addons/app-stirling-pdf
    target: stirling-pdf
    image: ccr.ccs.tencentyun.com/hassio-addons/stirling-pdf
  traccar:
    repository: hassio-addons/app-traccar
    target: traccar
    image: ccr.ccs.tencentyun.com/hassio-addons/traccar
  unifi:
    repository: hassio-addons/app-unifi
    target: unifi
    image: ccr.ccs.tencentyun.com/hassio-addons/unifi
  uptime-kuma:
    repository: hassio-addons/app-uptime-kuma
    target: uptime-kuma
    image: ccr.ccs.tencentyun.com/hassio-addons/uptime-kuma
  victoriametrics:
    repository: hassio-addons/app-victoriametrics
    target: victoriametrics
    image: ccr.ccs.tencentyun.com/hassio-addons/victoriametrics
  vscode:
    repository: hassio-addons/app-vscode
    target: vscode
    image: ccr.ccs.tencentyun.com/hassio-addons/vscode
  whisparr:
    repository: hassio-addons/app-whisparr
    target: whisparr
    image: ccr.ccs.tencentyun.com/hassio-addons/whisparr
  wireguard:
    repository: hassio-addons/app-wireguard
    target: wireguard
    image: ccr.ccs.tencentyun.com/hassio-addons/wireguard
  zerotier:
    repository: hassio-addons/app-zerotier
    target: zerotier
    image: ccr.ccs.tencentyun.com/hassio-addons/zerotier
  zwave-js-ui:
    repository: hassio-addons/app-zwave-js-ui
    target: zwave-js-ui
    image: ccr.ccs.tencentyun.com/hassio-addons/zwave-js-ui
